In [3]:
# Установка необходимых библиотек
# !pip install numpy opencv-python-headless


In [4]:
# !echo $CONDA_DEFAULT_ENV


In [5]:
# import os
# print(os.environ['CONDA_DEFAULT_ENV'])

In [6]:
# Установка необходимых библиотек
# !pip install  gdal


In [2]:
import os
import cv2
import numpy as np
from osgeo import gdal, osr
from osgeo import gdal
import json

In [3]:
def read_image(file_path):
    dataset = gdal.Open(file_path)
    if not dataset:
        raise FileNotFoundError(f"File not found: {file_path}")
    image = dataset.ReadAsArray()
    geo_transform = dataset.GetGeoTransform()
    projection = dataset.GetProjection()
    return image, geo_transform, projection

# Указание путей к папкам
source_folder = './1_20'  # Замените на реальный путь к папке 1_20
target_folder = './layouts'  # Замените на реальный путь к папке layouts

In [9]:
# Чтение первого изображения из папки 1_20
source_image_name = os.listdir(source_folder)[0]
source_image_path = os.path.join(source_folder, source_image_name)
source_image, source_geo_transform, source_projection = read_image(source_image_path)

In [10]:
print(source_image)

[[[ 631  619  708 ...  712  591  502]
  [ 690  731  734 ...  731  753  633]
  [ 712  754  711 ...  759  731  694]
  ...
  [ 654  674  513 ...  361  348  351]
  [ 688  616  447 ...  378  337  353]
  [ 773  663  397 ...  442  506  553]]

 [[ 842  821  948 ... 1035  846  704]
  [ 917  977  976 ... 1050 1083  896]
  [ 936 1000  937 ... 1092 1067 1011]
  ...
  [ 754  779  653 ...  347  342  330]
  [ 793  758  634 ...  407  358  373]
  [ 907  831  571 ...  611  655  718]]

 [[1250 1220 1388 ... 1409  990  707]
  [1347 1429 1435 ... 1451 1503 1101]
  [1251 1352 1264 ... 1520 1459 1351]
  ...
  [ 946  995  712 ...  389  389  384]
  [1016  890  568 ...  465  392  411]
  [1198 1004  469 ...  599  742  821]]

 [[2176 2103 2387 ... 2600 2660 2579]
  [2248 2390 2416 ... 2583 2622 2625]
  [2241 2350 2193 ... 2640 2673 2638]
  ...
  [1338 1281 2343 ...  472  483  435]
  [1345 1815 2834 ...  809  712  685]
  [1348 1860 2874 ... 2453 2000 2043]]]


In [11]:
print(source_geo_transform)

(0.0, 0.1, 0.0, 0.0, 0.0, 0.1)


In [12]:
print(source_projection)

GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]


In [13]:
# Чтение первого изображения из папки layouts
target_image_name = os.listdir(target_folder)[0]
target_image_path = os.path.join(target_folder, target_image_name)
target_image, target_geo_transform, target_projection = read_image(target_image_path)

In [14]:
target_image

array([[[ 474,  491,  477, ..., 2684, 2740, 2812],
        [ 523,  494,  454, ..., 2684, 2690, 2792],
        [ 533,  472,  457, ..., 2714, 2720, 2810],
        ...,
        [ 473,  542,  552, ...,    0,    0,    0],
        [ 438,  451,  461, ...,    0,    0,    0],
        [ 428,  438,  433, ...,    0,    0,    0]],

       [[ 779,  828,  836, ..., 2626, 2640, 2666],
        [ 841,  821,  797, ..., 2730, 2732, 2722],
        [ 816,  769,  754, ..., 2762, 2802, 2814],
        ...,
        [ 691,  705,  630, ...,    0,    0,    0],
        [ 698,  717,  690, ...,    0,    0,    0],
        [ 681,  665,  681, ...,    0,    0,    0]],

       [[ 366,  396,  375, ..., 2556, 2542, 2500],
        [ 379,  389,  355, ..., 2496, 2464, 2486],
        [ 412,  355,  363, ..., 2456, 2422, 2448],
        ...,
        [ 399,  470,  525, ...,    0,    0,    0],
        [ 352,  351,  405, ...,    0,    0,    0],
        [ 340,  342,  360, ...,    0,    0,    0]],

       [[5060, 5668, 6188, ..., 3588,

In [15]:
target_geo_transform

(399960.0, 10.0, 0.0, 5800020.0, 0.0, -10.0)

In [16]:
target_projection

'PROJCS["WGS 84 / UTM zone 37N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",39],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32637"]]'

In [17]:
print("Source Image Info:")
print(f"File: {source_image_name}")
print(f"Shape: {source_image.shape}")
print(f"GeoTransform: {source_geo_transform}")
print(f"Projection: {source_projection}")

print("\nTarget Image Info:")
print(f"File: {target_image_name}")
print(f"Shape: {target_image.shape}")
print(f"GeoTransform: {target_geo_transform}")
print(f"Projection: {target_projection}")

Source Image Info:
File: crop_0_0_0000.tif
Shape: (4, 211, 233)
GeoTransform: (0.0, 0.1, 0.0, 0.0, 0.0, 0.1)
Projection: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]

Target Image Info:
File: layout_2021-06-15.tif
Shape: (4, 10980, 10980)
GeoTransform: (399960.0, 10.0, 0.0, 5800020.0, 0.0, -10.0)
Projection: PROJCS["WGS 84 / UTM zone 37N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",39],PARAMETER["scale_factor",0.9996],PARAMETER[

In [18]:
def calculate_corners(geo_transform, width, height):
    """ Вспомогательная функция для вычисления координат углов изображения """
    ulx = geo_transform[0]
    uly = geo_transform[3]
    lrx = geo_transform[0] + width * geo_transform[1]
    lry = geo_transform[3] + height * geo_transform[5]
    return (ulx, uly), (lrx, lry)

In [19]:
# Вычисление углов для изображения из папки 1_20
source_ul, source_lr = calculate_corners(source_geo_transform, source_image.shape[2], source_image.shape[1])


In [20]:
# Вычисление углов для изображения из папки layouts
target_ul, target_lr = calculate_corners(target_geo_transform, target_image.shape[2], target_image.shape[1])


In [21]:
print("Source Image Corners (UL, LR):")
print(f"Upper Left: {source_ul}")
print(f"Lower Right: {source_lr}")

print("\nTarget Image Corners (UL, LR):")
print(f"Upper Left: {target_ul}")
print(f"Lower Right: {target_lr}")

Source Image Corners (UL, LR):
Upper Left: (0.0, 0.0)
Lower Right: (23.3, 21.1)

Target Image Corners (UL, LR):
Upper Left: (399960.0, 5800020.0)
Lower Right: (509760.0, 5690220.0)


In [22]:
# Вычисление масштаба
source_resolution = np.sqrt((source_lr[0] - source_ul[0])**2 + (source_lr[1] - source_ul[1])**2)
target_resolution = np.sqrt((target_lr[0] - target_ul[0])**2 + (target_lr[1] - target_ul[1])**2)
scale_factor = target_resolution / source_resolution

In [23]:
print(f"\nScale Factor: {scale_factor}")


Scale Factor: 4939.885564027744


In [24]:
# Масштабирование изображения из папки 1_20
resized_source_image = cv2.resize(source_image.transpose((1, 2, 0)), 
                                  (target_image.shape[2], target_image.shape[1]), 
                                  interpolation=cv2.INTER_AREA)

In [25]:
# Преобразуем обратно в исходный формат
resized_source_image = resized_source_image.transpose((2, 0, 1))

In [26]:
print(f"Resized Source Image Shape: {resized_source_image.shape}")

Resized Source Image Shape: (4, 10980, 10980)


Отлично, теперь, когда мы определили координаты углов и масштабировали сцену, следующим шагом будет определение и восстановление "битых" пикселей. Мы будем использовать средние значения соседних пикселей или медианные значения для замены "битых" пикселей.

In [27]:
def restore_pixels(image):
    """
    Восстановление "битых" пикселей, используя медианные значения соседних пикселей.
    """
    restored_image = image.copy()
    for band in range(image.shape[0]):
        band_data = image[band]
        mask = (band_data == 0) | (band_data < band_data.mean() * 0.15) | (band_data > band_data.mean() * 5)
        
        # Восстановление с использованием медианных значений соседних пикселей
        median = np.median(band_data[~mask])
        band_data[mask] = median
        restored_image[band] = band_data
    return restored_image

In [28]:
# Восстановление "битых" пикселей в изображении из папки 1_20
restored_source_image = restore_pixels(resized_source_image)

In [29]:
print("Restored Source Image")
print(f"Shape: {restored_source_image.shape}")

Restored Source Image
Shape: (4, 10980, 10980)


In [30]:
# Проверка восстановления на нескольких пикселях
restored_mask = (resized_source_image == 0) | (resized_source_image < resized_source_image.mean() * 0.15) | (resized_source_image > resized_source_image.mean() * 5)
print(f"Number of restored pixels: {np.sum(restored_mask)}")

Number of restored pixels: 19157


Шаг 4: Сохранение восстановленного изображения
Мы сохраним восстановленное изображение в формате GeoTIFF, используя библиотеку GDAL, чтобы сохранить географическую привязку и проекцию.

In [31]:
def save_image(image, file_path, geo_transform, projection):
    """
    Сохраняет изображение в формате GeoTIFF с указанной геопривязкой и проекцией.
    """
    driver = gdal.GetDriverByName('GTiff')
    dataset = driver.Create(file_path, image.shape[2], image.shape[1], image.shape[0], gdal.GDT_UInt16)
    dataset.SetGeoTransform(geo_transform)
    dataset.SetProjection(projection)
    for i in range(image.shape[0]):
        dataset.GetRasterBand(i+1).WriteArray(image[i])
    dataset.FlushCache()

In [32]:
# Путь для сохранения восстановленного изображения
output_image_path = './output_gpt/restored_source_image.tiff'  # Замените на желаемый путь для сохранения


In [33]:
# Сохранение восстановленного изображения
save_image(restored_source_image, output_image_path, target_geo_transform, target_projection)

print(f"Restored image saved to {output_image_path}")

Restored image saved to ./output_gpt/restored_source_image.tiff


Шаг 5: Формирование отчета
Мы добавим шаг для формирования и сохранения отчета о проделанной работе.

In [34]:
def generate_report(restored_image, source_image, target_image, source_geo_transform, target_geo_transform):
    """
    Формирует отчет о проделанной работе и сохраняет его в JSON формате.
    """
    report = {}
    
    # Основная информация об изображениях
    report['source_image_shape'] = source_image.shape
    report['target_image_shape'] = target_image.shape
    report['restored_image_shape'] = restored_image.shape

    # Координаты углов исходного изображения
    source_ul, source_lr = calculate_corners(source_geo_transform, source_image.shape[2], source_image.shape[1])
    report['source_image_corners'] = {
        'upper_left': [float(coord) for coord in source_ul],
        'lower_right': [float(coord) for coord in source_lr]
    }

    # Координаты углов восстановленного изображения
    restored_ul, restored_lr = calculate_corners(target_geo_transform, restored_image.shape[2], restored_image.shape[1])
    report['restored_image_corners'] = {
        'upper_left': [float(coord) for coord in restored_ul],
        'lower_right': [float(coord) for coord in restored_lr]
    }

    # Количество восстановленных пикселей
    restored_mask = (source_image == 0) | (source_image < source_image.mean() * 0.15) | (source_image > source_image.mean() * 5)
    report['number_of_restored_pixels'] = int(np.sum(restored_mask))

    # Сохранение отчета в файл
    report_path = './output/report.json'  # Замените на желаемый путь для сохранения
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=4)
    
    print(f"Report saved to {report_path}")

In [35]:
# Генерация отчета
generate_report(restored_source_image, source_image, target_image, source_geo_transform, target_geo_transform)

Report saved to ./output/report.json


Шаг 6: Итоговый отчет и проверка данных
Мы выведем информацию о всех обработанных изображениях и их характеристиках, чтобы убедиться, что все шаги выполнены правильно.

In [36]:
def print_final_report(restored_image, source_image, target_image, source_geo_transform, target_geo_transform):
    """
    Печатает итоговый отчет о проделанной работе.
    """
    # Вывод информации об изображениях
    print("Source Image Shape:", source_image.shape)
    print("Target Image Shape:", target_image.shape)
    print("Restored Image Shape:", restored_image.shape)
    
    # Координаты углов исходного изображения
    source_ul, source_lr = calculate_corners(source_geo_transform, source_image.shape[2], source_image.shape[1])
    print("Source Image Corners:")
    print("  Upper Left:", source_ul)
    print("  Lower Right:", source_lr)
    
    # Координаты углов восстановленного изображения
    restored_ul, restored_lr = calculate_corners(target_geo_transform, restored_image.shape[2], restored_image.shape[1])
    print("Restored Image Corners:")
    print("  Upper Left:", restored_ul)
    print("  Lower Right:", restored_lr)
    
    # Количество восстановленных пикселей
    restored_mask = (source_image == 0) | (source_image < source_image.mean() * 0.15) | (source_image > source_image.mean() * 5)
    print("Number of Restored Pixels:", np.sum(restored_mask))

In [37]:
# Печать итогового отчета
print_final_report(restored_source_image, source_image, target_image, source_geo_transform, target_geo_transform)

Source Image Shape: (4, 211, 233)
Target Image Shape: (4, 10980, 10980)
Restored Image Shape: (4, 10980, 10980)
Source Image Corners:
  Upper Left: (0.0, 0.0)
  Lower Right: (23.3, 21.1)
Restored Image Corners:
  Upper Left: (399960.0, 5800020.0)
  Lower Right: (509760.0, 5690220.0)
Number of Restored Pixels: 19


In [38]:
import os

def list_files(directory, extension=".tif"):
    """
    Возвращает список всех файлов с заданным расширением в указанной директории.
    """
    return [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith(extension)]

# Пути к папкам
source_directory = './1_20'  # Замените на реальный путь к папке 1_20
target_directory = './layouts'  # Замените на реальный путь к папке layouts

# Список файлов
source_files = list_files(source_directory)
target_files = list_files(target_directory)

print("Source Files:", source_files)
print("Target Files:", target_files)


Source Files: ['./1_20\\crop_0_0_0000.tif', './1_20\\crop_0_1_0000.tif', './1_20\\crop_0_2_0000.tif', './1_20\\crop_0_3_0000.tif', './1_20\\crop_1_0_0000.tif', './1_20\\crop_1_1_0000.tif', './1_20\\crop_1_2_0000.tif', './1_20\\crop_1_3_0000.tif', './1_20\\crop_2_0_0000.tif', './1_20\\crop_2_1_0000.tif', './1_20\\crop_2_2_0000.tif', './1_20\\crop_2_3_0000.tif', './1_20\\crop_3_0_0000.tif', './1_20\\crop_3_1_0000.tif', './1_20\\crop_3_2_0000.tif', './1_20\\crop_3_3_0000.tif', './1_20\\crop_4_0_0000.tif', './1_20\\crop_4_1_0000.tif', './1_20\\crop_4_2_0000.tif', './1_20\\crop_4_3_0000.tif']
Target Files: ['./layouts\\layout_2021-06-15.tif', './layouts\\layout_2021-08-16.tif', './layouts\\layout_2021-10-10.tif', './layouts\\layout_2022-03-17.tif']


In [40]:
def calculate_corners(geo_transform, width, height):
    ul_x = geo_transform[0]
    ul_y = geo_transform[3]
    lr_x = ul_x + geo_transform[1] * width
    lr_y = ul_y + geo_transform[5] * height
    return (ul_x, ul_y), (lr_x, lr_y)

def get_image_corners(file_path):
    image, geo_transform, _ = read_image(file_path)
    ul, lr = calculate_corners(geo_transform, image.shape[2], image.shape[1])
    return ul, lr

# Получение координат углов для всех изображений
source_image_corners = {file: get_image_corners(file) for file in source_files}
target_image_corners = {file: get_image_corners(file) for file in target_files}

print("Source Image Corners:", source_image_corners)
print("Target Image Corners:", target_image_corners)


Source Image Corners: {'./1_20\\crop_0_0_0000.tif': ((0.0, 0.0), (23.3, 21.1)), './1_20\\crop_0_1_0000.tif': ((0.0, 0.0), (22.400000000000002, 19.200000000000003)), './1_20\\crop_0_2_0000.tif': ((0.0, 0.0), (24.700000000000003, 21.400000000000002)), './1_20\\crop_0_3_0000.tif': ((0.0, 0.0), (23.3, 21.1)), './1_20\\crop_1_0_0000.tif': ((0.0, 0.0), (19.400000000000002, 24.0)), './1_20\\crop_1_1_0000.tif': ((0.0, 0.0), (21.3, 18.2)), './1_20\\crop_1_2_0000.tif': ((0.0, 0.0), (26.6, 20.200000000000003)), './1_20\\crop_1_3_0000.tif': ((0.0, 0.0), (21.8, 20.5)), './1_20\\crop_2_0_0000.tif': ((0.0, 0.0), (20.8, 19.200000000000003)), './1_20\\crop_2_1_0000.tif': ((0.0, 0.0), (19.5, 27.1)), './1_20\\crop_2_2_0000.tif': ((0.0, 0.0), (20.3, 23.0)), './1_20\\crop_2_3_0000.tif': ((0.0, 0.0), (21.8, 24.400000000000002)), './1_20\\crop_3_0_0000.tif': ((0.0, 0.0), (21.8, 19.8)), './1_20\\crop_3_1_0000.tif': ((0.0, 0.0), (18.2, 18.5)), './1_20\\crop_3_2_0000.tif': ((0.0, 0.0), (18.3, 26.3)), './1_20\\c

In [41]:
def check_intersection(source_ul, source_lr, target_ul, target_lr):
    """
    Проверяет пересечение между двумя прямоугольниками.
    """
    return not (source_lr[0] < target_ul[0] or source_ul[0] > target_lr[0] or 
                source_lr[1] > target_ul[1] or source_ul[1] < target_lr[1])

def find_matching_target_file(source_corners, target_image_corners):
    """
    Ищет соответствующий файл из target_image_corners для заданного source_corners.
    """
    source_ul, source_lr = source_corners
    for target_file, target_corners in target_image_corners.items():
        target_ul, target_lr = target_corners
        if check_intersection(source_ul, source_lr, target_ul, target_lr):
            return target_file
    return None

# Проверка сопоставления файлов
for source_file, source_corners in source_image_corners.items():
    target_file = find_matching_target_file(source_corners, target_image_corners)
    print(f"Source file: {source_file}, Target file: {target_file}")


Source file: ./1_20\crop_0_0_0000.tif, Target file: None
Source file: ./1_20\crop_0_1_0000.tif, Target file: None
Source file: ./1_20\crop_0_2_0000.tif, Target file: None
Source file: ./1_20\crop_0_3_0000.tif, Target file: None
Source file: ./1_20\crop_1_0_0000.tif, Target file: None
Source file: ./1_20\crop_1_1_0000.tif, Target file: None
Source file: ./1_20\crop_1_2_0000.tif, Target file: None
Source file: ./1_20\crop_1_3_0000.tif, Target file: None
Source file: ./1_20\crop_2_0_0000.tif, Target file: None
Source file: ./1_20\crop_2_1_0000.tif, Target file: None
Source file: ./1_20\crop_2_2_0000.tif, Target file: None
Source file: ./1_20\crop_2_3_0000.tif, Target file: None
Source file: ./1_20\crop_3_0_0000.tif, Target file: None
Source file: ./1_20\crop_3_1_0000.tif, Target file: None
Source file: ./1_20\crop_3_2_0000.tif, Target file: None
Source file: ./1_20\crop_3_3_0000.tif, Target file: None
Source file: ./1_20\crop_4_0_0000.tif, Target file: None
Source file: ./1_20\crop_4_1_00

In [44]:
def process_multiple_images(source_files, source_image_corners, target_image_corners, output_directory):
    """
    Обрабатывает несколько исходных изображений, сопоставляя их с соответствующими целевыми изображениями.
    """
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
    
    for source_file in source_files:
        target_file = find_matching_target_file(source_image_corners[source_file], target_image_corners)
        if target_file:
            print(f"Processing source file: {source_file} with target file: {target_file}")
            
            source_image, source_geo_transform, source_projection = read_image(source_file)
            target_image, target_geo_transform, target_projection = read_image(target_file)
            
            resized_source_image = resize_image(source_image, target_image.shape[2], target_image.shape[1])
            restored_source_image = restore_pixels(resized_source_image)
            
            output_image_path = os.path.join(output_directory, os.path.basename(source_file))
            save_image(restored_source_image, output_image_path, target_geo_transform, target_projection)
            
            generate_report(restored_source_image, source_image, target_image, source_geo_transform, target_geo_transform)
        else:
            print(f"No matching target file found for source file: {source_file}")

# Путь к папке для сохранения результатов
output_directory = './output'  # Замените на желаемый путь для сохранения результатов

# Запуск обработки нескольких изображений
process_multiple_images(source_files, source_image_corners, target_image_corners, output_directory)


No matching target file found for source file: ./1_20\crop_0_0_0000.tif
No matching target file found for source file: ./1_20\crop_0_1_0000.tif
No matching target file found for source file: ./1_20\crop_0_2_0000.tif
No matching target file found for source file: ./1_20\crop_0_3_0000.tif
No matching target file found for source file: ./1_20\crop_1_0_0000.tif
No matching target file found for source file: ./1_20\crop_1_1_0000.tif
No matching target file found for source file: ./1_20\crop_1_2_0000.tif
No matching target file found for source file: ./1_20\crop_1_3_0000.tif
No matching target file found for source file: ./1_20\crop_2_0_0000.tif
No matching target file found for source file: ./1_20\crop_2_1_0000.tif
No matching target file found for source file: ./1_20\crop_2_2_0000.tif
No matching target file found for source file: ./1_20\crop_2_3_0000.tif
No matching target file found for source file: ./1_20\crop_3_0_0000.tif
No matching target file found for source file: ./1_20\crop_3_1_0

In [45]:
def calculate_new_corners(geo_transform, width, height, start_x, start_y, step_x, step_y):
    ul_x = start_x + geo_transform[1] * width
    ul_y = start_y + geo_transform[5] * height
    lr_x = ul_x + step_x * width
    lr_y = ul_y + step_y * height
    return (ul_x, ul_y), (lr_x, lr_y)

def get_new_image_corners(file_path, start_x, start_y, step_x, step_y):
    image, geo_transform, _ = read_image(file_path)
    ul, lr = calculate_new_corners(geo_transform, image.shape[2], image.shape[1], start_x, start_y, step_x, step_y)
    return ul, lr

# Начальные координаты и шаги
start_x, start_y = 400000, 5800000  # Задайте реальные начальные координаты
step_x, step_y = 1000, 1000  # Задайте реальные шаги по X и Y

# Получение новых координат углов для всех изображений в `1_20`
new_source_image_corners = {file: get_new_image_corners(file, start_x, start_y, step_x, step_y) for file in source_files}

print("New Source Image Corners:", new_source_image_corners)


New Source Image Corners: {'./1_20\\crop_0_0_0000.tif': ((400023.3, 5800021.1), (633023.3, 6011021.1)), './1_20\\crop_0_1_0000.tif': ((400022.4, 5800019.2), (624022.4, 5992019.2)), './1_20\\crop_0_2_0000.tif': ((400024.7, 5800021.4), (647024.7, 6014021.4)), './1_20\\crop_0_3_0000.tif': ((400023.3, 5800021.1), (633023.3, 6011021.1)), './1_20\\crop_1_0_0000.tif': ((400019.4, 5800024.0), (594019.4, 6040024.0)), './1_20\\crop_1_1_0000.tif': ((400021.3, 5800018.2), (613021.3, 5982018.2)), './1_20\\crop_1_2_0000.tif': ((400026.6, 5800020.2), (666026.6, 6002020.2)), './1_20\\crop_1_3_0000.tif': ((400021.8, 5800020.5), (618021.8, 6005020.5)), './1_20\\crop_2_0_0000.tif': ((400020.8, 5800019.2), (608020.8, 5992019.2)), './1_20\\crop_2_1_0000.tif': ((400019.5, 5800027.1), (595019.5, 6071027.1)), './1_20\\crop_2_2_0000.tif': ((400020.3, 5800023.0), (603020.3, 6030023.0)), './1_20\\crop_2_3_0000.tif': ((400021.8, 5800024.4), (618021.8, 6044024.4)), './1_20\\crop_3_0_0000.tif': ((400021.8, 5800019.

In [46]:
def check_new_intersection(source_ul, source_lr, target_ul, target_lr):
    return not (source_lr[0] < target_ul[0] or source_ul[0] > target_lr[0] or 
                source_lr[1] > target_ul[1] or source_ul[1] < target_lr[1])

def find_new_matching_target_file(source_corners, target_image_corners):
    source_ul, source_lr = source_corners
    for target_file, target_corners in target_image_corners.items():
        target_ul, target_lr = target_corners
        if check_new_intersection(source_ul, source_lr, target_ul, target_lr):
            return target_file
    return None

# Проверка сопоставления файлов с новыми координатами
for source_file, source_corners in new_source_image_corners.items():
    target_file = find_new_matching_target_file(source_corners, target_image_corners)
    print(f"Source file: {source_file}, Target file: {target_file}")


Source file: ./1_20\crop_0_0_0000.tif, Target file: None
Source file: ./1_20\crop_0_1_0000.tif, Target file: None
Source file: ./1_20\crop_0_2_0000.tif, Target file: None
Source file: ./1_20\crop_0_3_0000.tif, Target file: None
Source file: ./1_20\crop_1_0_0000.tif, Target file: None
Source file: ./1_20\crop_1_1_0000.tif, Target file: None
Source file: ./1_20\crop_1_2_0000.tif, Target file: None
Source file: ./1_20\crop_1_3_0000.tif, Target file: None
Source file: ./1_20\crop_2_0_0000.tif, Target file: None
Source file: ./1_20\crop_2_1_0000.tif, Target file: None
Source file: ./1_20\crop_2_2_0000.tif, Target file: None
Source file: ./1_20\crop_2_3_0000.tif, Target file: None
Source file: ./1_20\crop_3_0_0000.tif, Target file: None
Source file: ./1_20\crop_3_1_0000.tif, Target file: None
Source file: ./1_20\crop_3_2_0000.tif, Target file: None
Source file: ./1_20\crop_3_3_0000.tif, Target file: None
Source file: ./1_20\crop_4_0_0000.tif, Target file: None
Source file: ./1_20\crop_4_1_00

In [47]:
start_x, start_y = 400000, 5800000  # Замените на реальные начальные координаты
step_x, step_y = 1000, 1000  # Замените на реальные шаги по X и Y


In [48]:
def calculate_new_corners(geo_transform, width, height, start_x, start_y, step_x, step_y):
    ul_x = start_x + geo_transform[1] * width
    ul_y = start_y + geo_transform[5] * height
    lr_x = ul_x + step_x * width
    lr_y = ul_y + step_y * height
    return (ul_x, ul_y), (lr_x, lr_y)

def get_new_image_corners(file_path, start_x, start_y, step_x, step_y):
    image, geo_transform, _ = read_image(file_path)
    ul, lr = calculate_new_corners(geo_transform, image.shape[2], image.shape[1], start_x, start_y, step_x, step_y)
    return ul, lr

# Получение новых координат углов для всех изображений в `1_20`
new_source_image_corners = {file: get_new_image_corners(file, start_x, start_y, step_x, step_y) for file in source_files}

print("New Source Image Corners:", new_source_image_corners)


New Source Image Corners: {'./1_20\\crop_0_0_0000.tif': ((400023.3, 5800021.1), (633023.3, 6011021.1)), './1_20\\crop_0_1_0000.tif': ((400022.4, 5800019.2), (624022.4, 5992019.2)), './1_20\\crop_0_2_0000.tif': ((400024.7, 5800021.4), (647024.7, 6014021.4)), './1_20\\crop_0_3_0000.tif': ((400023.3, 5800021.1), (633023.3, 6011021.1)), './1_20\\crop_1_0_0000.tif': ((400019.4, 5800024.0), (594019.4, 6040024.0)), './1_20\\crop_1_1_0000.tif': ((400021.3, 5800018.2), (613021.3, 5982018.2)), './1_20\\crop_1_2_0000.tif': ((400026.6, 5800020.2), (666026.6, 6002020.2)), './1_20\\crop_1_3_0000.tif': ((400021.8, 5800020.5), (618021.8, 6005020.5)), './1_20\\crop_2_0_0000.tif': ((400020.8, 5800019.2), (608020.8, 5992019.2)), './1_20\\crop_2_1_0000.tif': ((400019.5, 5800027.1), (595019.5, 6071027.1)), './1_20\\crop_2_2_0000.tif': ((400020.3, 5800023.0), (603020.3, 6030023.0)), './1_20\\crop_2_3_0000.tif': ((400021.8, 5800024.4), (618021.8, 6044024.4)), './1_20\\crop_3_0_0000.tif': ((400021.8, 5800019.

In [49]:
def check_new_intersection(source_ul, source_lr, target_ul, target_lr):
    return not (source_lr[0] < target_ul[0] or source_ul[0] > target_lr[0] or 
                source_lr[1] > target_ul[1] or source_ul[1] < target_lr[1])

def find_new_matching_target_file(source_corners, target_image_corners):
    source_ul, source_lr = source_corners
    for target_file, target_corners in target_image_corners.items():
        target_ul, target_lr = target_corners
        if check_new_intersection(source_ul, source_lr, target_ul, target_lr):
            return target_file
    return None

# Проверка сопоставления файлов с новыми координатами
for source_file, source_corners in new_source_image_corners.items():
    target_file = find_new_matching_target_file(source_corners, target_image_corners)
    print(f"Source file: {source_file}, Target file: {target_file}")


Source file: ./1_20\crop_0_0_0000.tif, Target file: None
Source file: ./1_20\crop_0_1_0000.tif, Target file: None
Source file: ./1_20\crop_0_2_0000.tif, Target file: None
Source file: ./1_20\crop_0_3_0000.tif, Target file: None
Source file: ./1_20\crop_1_0_0000.tif, Target file: None
Source file: ./1_20\crop_1_1_0000.tif, Target file: None
Source file: ./1_20\crop_1_2_0000.tif, Target file: None
Source file: ./1_20\crop_1_3_0000.tif, Target file: None
Source file: ./1_20\crop_2_0_0000.tif, Target file: None
Source file: ./1_20\crop_2_1_0000.tif, Target file: None
Source file: ./1_20\crop_2_2_0000.tif, Target file: None
Source file: ./1_20\crop_2_3_0000.tif, Target file: None
Source file: ./1_20\crop_3_0_0000.tif, Target file: None
Source file: ./1_20\crop_3_1_0000.tif, Target file: None
Source file: ./1_20\crop_3_2_0000.tif, Target file: None
Source file: ./1_20\crop_3_3_0000.tif, Target file: None
Source file: ./1_20\crop_4_0_0000.tif, Target file: None
Source file: ./1_20\crop_4_1_00